language: go

go:
  - 1.6
  - 1.7
  - tip

script:
  - go vet
  - go test -cover -coverprofile=coverage.out
  - go build -a -tags netgo

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8c775eddeab017630645
    on_success: change
    on_failure: always
    on_start: never
